### PR TITLE
Added device details page

### LINKED ISSUE #10: Create Device Page
### Task
- Create a page for a specific device after user clicks on it
- Should include capacity and feel free to use component libraries

Complete by: 8/31

### PR DESCRIPTION
**Pull request by alejandro-garf**
Related Issue: Closes #10 

### Description
- Added a device details page with dummy data. 
- Tried to make it dynamic but ran into some issues, instead all if the device ids lead to the same device page when clicked
- This may be ideal since we will only be importing data from one sensor, keeps it simple
- Can talk about future development in making it dynamic with every device id. 

### Images
Screenshot 2024-08-27 at 3 06 17 PM

Remember to request for review

### CODE REVIEW

**Comment by MatthewCCChang** [comment]
Instead of the bar, can you add some kind of component from the component library that has some kind of measurement so users can tell easily without looking at the specific number. Keep the percentage though. Otherwise, LGTM

**Comment by alejandro-garf** [comment]
I tried using a component library but it messed up the formatting of the rest of the site so I created a dynamic progress bar component. I know you don't want a progress bar tho so I can make something else like a pie chart, just let me know. 
Screenshot 2024-08-30 at 1 48 55 PM

**Comment by MatthewCCChang** [comment]
Progress bar seems fine i think we can have different colors for severity so like red for 90% full and orange and green for regular and moderate. The point is to setup some kind of alert to the users so when they see the progress bar then they'll be able to figure out how full it is at first glance.

**Comment by alejandro-garf** [comment]
I added the color component to the progress bar, I made it to follow 0 - 30% is green, 31 - 70 is yellow and 71 - 100 is red. Let me know if you'd like me to build on this more 
Screenshot 2024-09-02 at 12 08 38 PM
Screenshot 2024-09-02 at 12 08 28 PM
Screenshot 2024-09-02 at 12 08 13 PM

**Pull request merged**
